- .gitignore
- docs/examples/cloud_monitoring/README.rst
- docs/examples/cloud_monitoring/basic_metrics.py
- docs/examples/cloud_trace_exporter/README.rst
- docs/examples/cloud_trace_exporter/basic_trace.py
- opentelemetry-exporter-cloud-monitoring/CHANGELOG.md
- opentelemetry-exporter-cloud-monitoring/LICENSE
- opentelemetry-exporter-cloud-monitoring/MANIFEST.in
- opentelemetry-exporter-cloud-monitoring/README.rst
- opentelemetry-exporter-cloud-monitoring/setup.cfg
- opentelemetry-exporter-cloud-monitoring/setup.py
- opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
- opentelemetry-exporter-cloud-monitoring/tests/test_cloud_monitoring.py
- opentelemetry-exporter-cloud-trace/CHANGELOG.md
- opentelemetry-exporter-cloud-trace/LICENSE
- opentelemetry-exporter-cloud-trace/MANIFEST.in
- opentelemetry-exporter-cloud-trace/README.rst
- opentelemetry-exporter-cloud-trace/setup.cfg
- opentelemetry-exporter-cloud-trace/setup.py
- opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/cloud_trace_propagator.py
- opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-exporter-cloud-trace/src/opentelemetry/tools/resource_detector.py
- opentelemetry-exporter-cloud-trace/tests/test_cloud_trace_exporter.py
- opentelemetry-exporter-cloud-trace/tests/test_cloud_trace_propagator.py
- opentelemetry-exporter-cloud-trace/tests/test_gcp_resource_detector.py
No actual newly written code here, this is all copied over from the opentelemetry-python repo. Also added a gitignore:
```bash
cp -R ../opentelemetry-python/ext/opentelemetry-exporter-cloud-* .
mkdir -p docs/examples && cp -R ../opentelemetry-python/docs/examples/cloud_* docs/examples/.
curl https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore  > .gitignore
```
The next PR will have a basic tox set up, then I will work on CI.
> Copied over files from opentelemetry-python repo

- docs/examples/cloud_monitoring/basic_metrics.py
- opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-cloud-monitoring/tests/test_cloud_monitoring.py
Copied from https://github.com/open-telemetry/opentelemetry-python/pull/898, also addressed @aabmass's comments
> Handle statefulness in Cloud Monitoring exporter

- opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-exporter-cloud-trace/tests/test_cloud_trace_exporter.py
Fixing a floating point error caused by using 1e9 instead of 10**9
> fix floating point error

- docs/examples/tools/cloud_resource_detector/README.rst
A user ran into some trouble setting up the GKE resource detector. This troubleshooting section contains some common problems and solutions.
> add troubleshooting section for GKE resources

- dev-constraints.txt
- opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring.py
`HistogramAggregator` is new with the Views API. Don't think this can be merged until 0.12.0 is released (or how does our releasing process work?)
> Histogram support for monitoring exporter

- opentelemetry-exporter-google-cloud/CHANGELOG.md
> Update changelog for #58

- opentelemetry-exporter-google-cloud/setup.cfg
> set upper bounds for google client libs

- docs-requirements.txt
- docs/examples/cloud_trace_exporter/README.rst
- docs/examples/cloud_trace_exporter/advanced_trace.py
- opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-tools-google-cloud/setup.cfg
Fixes #76, fixes #77 
Will cut a release after this PR is merged 🙂
> add dependency version specifiers and update docs for span processors

- opentelemetry-exporter-google-cloud/CHANGELOG.md
- opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/google/version.py
- opentelemetry-tools-google-cloud/CHANGELOG.md
- opentelemetry-tools-google-cloud/src/opentelemetry/tools/google/version.py
Reverts GoogleCloudPlatform/opentelemetry-operations-python#86
Should have been commited with "Rebase and Merge".
> Revert "release pr/0.14b0"

- dev-constraints.txt
- opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring.py
- tox.ini
Build against opentelemetry 0.16b1 packages and make a few small fixes.
> upgrade to opentelemetry API/SDK 0.16b1

- dev-constraints.txt
- opentelemetry-exporter-google-cloud/mypy.ini
- opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-tools-google-cloud/mypy.ini
- tox.ini
MyPy v0.800 has the big fix fix of improved namespace package support. So, I can delete the `__init__.pyi` files which were a hack for mypy.
> Upgrade mypy to v0.800

- .github/header-checker-lint.yml
Add a header check config. The config will take effect after this PR is merged
> add header checker config

- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
> Remove pragma for undefined type in OTel SDK

- .github/header-checker-lint.yml
- cloudbuild-e2e-gce.yaml
- cloudbuild-e2e-gke.yaml
- cloudbuild-e2e-image.yaml
- cloudbuild-e2e-local.yaml
- docs/conf.py
- docs/examples/cloud_trace_exporter/advanced_trace.py
- docs/examples/cloud_trace_exporter/basic_trace.py
- e2e-test-server/Dockerfile
- e2e-test-server/e2e_test_server/constants.py
- e2e-test-server/e2e_test_server/scenarios.py
- e2e-test-server/e2e_test_server/server.py
- e2e-test-server/main.py
- e2e-test-server/wait-for-image.sh
- get_mock_server.sh
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/_time.py
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/__init__.py
- release.py
- test-common/setup.py
- test-common/src/test_common/__init__.py
- test-common/src/test_common/base_exporter_integration_test.py
Fixes #149 
```sh
perl -i -p -e 's/(202\d Google)$/$1 LLC/' $(git ls-files)
```
> add LLC to copyright headers

- cloudbuild-e2e-gce.yaml
- cloudbuild-e2e-gke.yaml
- cloudbuild-e2e-local.yaml
- e2e-test-server/e2e_test_server/scenarios.py
Implement complexTrace scenario and bump the version of test runner to test the structure.
> implement complexTrace scenario upgrade test runner

- .isort.cfg
- dev-constraints.txt
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-gcp-monitoring/tests/test_cloud_monitoring.py
- opentelemetry-exporter-gcp-monitoring/tests/test_cloud_monitoring_exporter_integration.py
- opentelemetry-exporter-gcp-trace/setup.py
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_exporter.py
- opentelemetry-exporter-gcp-trace/tests/test_integration_cloud_trace_exporter.py
- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/__init__.py
- opentelemetry-propagator-gcp/tests/test_cloud_trace_propagator.py
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/__init__.py
- tox.ini
> Upgrade dev dependencies and reformat the code

- cloudbuild-e2e-gce.yaml
- cloudbuild-e2e-gke.yaml
- cloudbuild-e2e-local.yaml
- e2e-test-server/Dockerfile
- e2e-test-server/e2e_test_server/scenarios.py
- e2e-test-server/requirements.txt
Test case passing
```
=== RUN   TestBasicPropagator
INFO:e2e_test_server.server:publishing data=b'' and attributes={'test_id': '16368302953904539254', 'status_code': '0'}
trace_test.go:91: Retrying ListSpans: Got zero spans in trace
--- PASS: TestBasicPropagator (3.55s)
```
> Implement basicPropagator scenario

- docs/examples/cloud_trace_propagator/client.py
- docs/examples/cloud_trace_propagator/server.py
> Fix Wrong Imports on Cloud Trace Propogator

- dev-constraints.txt
- docs-requirements.txt
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_exporter.py
- tox.ini
- Fix tests for newer versions of SDK which automatically drop invalid attributes
- Upgrade mypy version
- Fix a deprecation warning from `collections.Sequence` use.
> Fix tests and other maintenance

- docs/examples/cloud_trace_propagator/README.rst
- docs/examples/cloud_trace_propagator/client.py
- docs/examples/cloud_trace_propagator/server.py
> Fix propagator example

- opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
- opentelemetry-exporter-gcp-trace/CHANGELOG.md
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-propagator-gcp/CHANGELOG.md
- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
- opentelemetry-resourcedetector-gcp/CHANGELOG.md
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py
- Release 1.1.0 (Part 1/2) release commit
- Release 1.1.0 (Part 2/2) bump version to 1.2.0.dev0
I will merge with "rebase and merge" to get two commits
> Release versions 1.1.0 and 1.1.0a0

- opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
- opentelemetry-exporter-gcp-trace/CHANGELOG.md
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-propagator-gcp/CHANGELOG.md
- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
- opentelemetry-resourcedetector-gcp/CHANGELOG.md
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py
- Release 1.2.0 (Part 1/2) release commit
- Release 1.2.0 (Part 2/2) bump version to 1.3.0.dev0
> release pr/1.2.0

- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/__init__.py
- opentelemetry-propagator-gcp/tests/test_cloud_trace_propagator.py
> Make the trace flags optional when parsing x-cloud-trace-context

- opentelemetry-resourcedetector-gcp/setup.cfg
> Remove google-auth dependency for resource detection

- opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
- opentelemetry-exporter-gcp-trace/CHANGELOG.md
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-propagator-gcp/CHANGELOG.md
- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
- opentelemetry-resourcedetector-gcp/CHANGELOG.md
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py
- Release 1.3.0 (Part 1/2) release commit
- Release 1.3.0 (Part 2/2) bump version to 1.4.0.dev0
> release pr/1.3.0

- dev-constraints.txt
- opentelemetry-exporter-gcp-monitoring/mypy.ini
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-gcp-trace/mypy.ini
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-propagator-gcp/mypy.ini
- opentelemetry-resourcedetector-gcp/mypy.ini
- tox.ini
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/56
no diff in snapshot tests
> Use protobuf objects with types instead of dicts

- opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
- opentelemetry-exporter-gcp-trace/CHANGELOG.md
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-propagator-gcp/CHANGELOG.md
- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
- opentelemetry-resourcedetector-gcp/CHANGELOG.md
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py
- Release 1.4.0 (Part 1/2) release commit
- Release 1.4.0 (Part 2/2) bump version to 1.5.0
Made following https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/docs/releasing.md#run-release-script
- Make sure you review the the commits in the PR INDIVIDUALLY. The first commit (a) will be tagged as the release in the next step, so it needs to be correct.
- After review, merge your PR with ["Rebase and merge"](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#rebase-and-merge-your-pull-request-commits) on github. This is crucial; if you use the regular "Squash and merge", you will not have the two sequential commits you need to create a release tag.
> release pr/1.4.0

- .circleci/config.yml
- .github/workflows/ci.yaml
> Create initial github workflow file

- .github/workflows/ci.yaml
Part of #225 
I'll delete the CircleCI config and turn off the project in a final PR.
> Migrate circleci config to github workflow

- opentelemetry-resourcedetector-gcp/tests/__snapshots__/test_detector.ambr
Ran `tox -f py310-ci-test -- --snapshot-update` to update all snapshots
> Update snapshots for bumped upstream version to fix CI

- docs/conf.py
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/144
This was mostly fixed already.
> Update copyright from "Google" -> "Google LLC" where needed

- opentelemetry-exporter-gcp-monitoring/setup.cfg
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/environment_variables.py
- opentelemetry-exporter-gcp-monitoring/tests/test_cloud_monitoring_auto_instrument.py
> Add autoinstrumentation entrypoint for monitoring exporter

- opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
- opentelemetry-exporter-gcp-trace/CHANGELOG.md
- opentelemetry-resourcedetector-gcp/CHANGELOG.md
These were forgotten in the respective PRs.
> Add changelog entries for PRs since last release

- docs/index.rst
The ones listed here are deprecated packages.
> Fix badges in documentation

- samples/otlptrace/README.md
- samples/otlptrace/example_grpc.py
- Removes extraneous parameter `insecure`.
- Removes redundant `refresh` cal for credentials.
- Update readme.
> Address minor feedback for the grpc sample

- .pylintrc
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
- opentelemetry-exporter-gcp-monitoring/tests/fixtures/gcmfake.py
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
- opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_exporter.py
This code has suffered from some bit rot while new dependency versions came out. Lint issues are caused by https://github.com/protocolbuffers/protobuf/issues/10372
> Fix broken test that relied on patching internals and lint

- docs/examples/cloud_resource_detector/resource_detector_metrics.py
- docs/examples/cloud_resource_detector/resource_detector_trace.py
- docs/examples/cloud_trace_exporter/basic_trace.py
- Remove any usage of SimpleSpanProcessor
- Fix import paths for resource detector which were missed earlier
- Fix use of pre-1.0 metrics SDK
> Update a few examples broken or misleading examples

- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/__init__.py
Add a 5 seconds timeout to a requests call that missed it.
> gcp_resource_detector: add missing timeout to requests call

- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_constants.py
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_detector.py
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_faas.py
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_metadata.py
- opentelemetry-resourcedetector-gcp/tests/__snapshots__/test_detector.ambr
- opentelemetry-resourcedetector-gcp/tests/test_detector.py
- opentelemetry-resourcedetector-gcp/tests/test_faas.py
Copied from JS/Go implementations. Subsequent PRs for e2e tests:
- https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/347
- https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/349
> Implement Cloud Run and Cloud Functions faas resource detection

- e2e-test-server/e2e_test_server/scenarios.py
Un-skip (enable) the resource detection scenario for Cloud Run
> Enable e2e resource detection test for Cloud Run

- cloudbuild-e2e-gae.yaml
- e2e-test-server/e2e_test_server/server.py
Added the Cloud Build file and health checks needed for GAE
Ignore the **GAE Standard** failure, it is coming in the next PR
Manually verified the span as well
> Run e2e tests on GAE flex

- opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
- opentelemetry-exporter-gcp-trace/CHANGELOG.md
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-propagator-gcp/CHANGELOG.md
- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
- opentelemetry-resourcedetector-gcp/CHANGELOG.md
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py
- **Release 1.7.0 (Part 1/2) release commit**
- **Release 1.7.0 (Part 2/2) bump version to 1.8.0.dev0**
Created following [releasing.md](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/docs/releasing.md). Will be merged with "Rebase and Merge" to generate two commits in main
> release pr/1.7.0

- opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
- opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
- opentelemetry-exporter-gcp-trace/CHANGELOG.md
- opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
- opentelemetry-propagator-gcp/CHANGELOG.md
- opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
- opentelemetry-resourcedetector-gcp/CHANGELOG.md
- opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py
Created release PR following https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/docs/releasing.md#open-and-merge-a-pr
- **Release 1.8.0 (Part 1/2) release commit**
- **Release 1.8.0 (Part 2/2) bump version to 1.9.0.dev0**
> release pr/1.8.0
