.flake8
.gitignore
.isort.cfg
.pylintrc
dev-constraints.txt
opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-cloud-monitoring/tests/test_cloud_monitoring.py
opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/cloud_trace_propagator.py
opentelemetry-exporter-cloud-trace/src/opentelemetry/tools/resource_detector.py
opentelemetry-exporter-cloud-trace/tests/test_cloud_trace_exporter.py
opentelemetry-exporter-cloud-trace/tests/test_cloud_trace_propagator.py
pyproject.toml
tox.ini

Copied over `.flake8`, `.isort.cfg`, `.pylintrc`, and `pyproject.toml` (black config) from opentelemetry-python and removed any references to directories not in this new repo.
I added a `tox.ini` file similar to the one in opentelemetry-python, but I changed a few things up:
- Added a tox factor `ci` for any envs that should run during CI. That way you can quickly run `tox -f ci -pauto` to see what would run in CI
- Added a constant `opentelemetry_python_commit` which is the commit hash in opentelemetry-python repo that CI should run against.
* For now, the opentelemetry-python repo is changing rapidly between releases, and development here is concurrent with that
* CI won't flake as opentelemetry-python changes
* If you go through commit history, you can see what is the corresponding …

Set up tox to run linters and tests

---

.circleci/config.yml
tox.ini

Run tests and lint in CircleCI for pull requests. Part of #16 
- run all tox factors per python environment
- run lint
- [cache pip wheels at `~/.cache/pip`](https://circleci.com/docs/2.0/caching/)
- [write junit.xml for circleci to track individual tests](https://circleci.com/docs/2.0/collect-test-data/#pytest)

Added CircleCI config.yml

---

.circleci/config.yml
.gitignore
docs/Makefile
docs/cloud_monitoring/cloud_monitoring.rst
docs/cloud_trace/cloud_trace.rst
docs/conf.py
docs/index.rst
docs/make.bat
tox.ini

Ran `sphinx-quickstart` and then added a few configuration options to the default theme. I also had to copy over `cloud_monitoring.rst` and `cloud_trace.rst` from the opentelemetry-python repo.
Added tox env to build the docs `tox -e docs` and a tox ci env to build docs in ci. Updated CircleCI to run it.
Next, I will set up readthedocs.io to build these.
Closes #27.

Added sphinx files and basic configuration

---

opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-cloud-monitoring/tests/test_cloud_monitoring.py

The aggregation method that ValueObserver uses, ValueObserverAggregator was previously unsupported. After offline discussion with @aabmass and @cnnradams we agreed on a method of representing this info in Cloud Monitoring.
Resolves https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/18

Add support for ValueObserver

---

.readthedocs.yml
dev-constraints.txt
docs-requirements.txt
tox.ini

Added `.readthedocs.yml` config to build sphinx docs, and also added a webhook for them to update on pushes and PRs. You can see the builds/docs, including those for PRs, here: https://readthedocs.org/projects/google-cloud-opentelemetry/builds/. Here is the built docs for this PR: https://google-cloud-opentelemetry--34.org.readthedocs.build/en/34/
Unfortunately I can't set up the PR status check which would add a link to each PR because without giving ReadTheDocs access to the GoogleCloudPlatform github org.
Last thing to note, I had to move the opentelemetry-python commit hash to `dev-constraints.txt` because ReadTheDocs won't let you specify a build command, you have to give it the dependencies and this was the easiest reusable way to do that. Unfortunately, because tox can't detect …

Add config for readthedocs

---

.gitignore
README.md
docs/_templates/custom-class-template.rst
docs/_templates/custom-module-template.rst
docs/apireference.rst
docs/cloud_monitoring/cloud_monitoring.rst
docs/cloud_trace/cloud_trace.rst
docs/conf.py
docs/contributing.md
docs/index.rst
opentelemetry-exporter-cloud-monitoring/README.rst
opentelemetry-exporter-cloud-trace/README.rst

Check out the built docs to see all of these changes here: https://google-cloud-opentelemetry--39.org.readthedocs.build/en/39/
- Use [Sphinx autosummary](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) to recursively create stub files with `..autodoc` directives.
* Mostly did this following [these instructions](https://stackoverflow.com/questions/2701998/sphinx-autodoc-is-not-automatic-enough/62613202#62613202). This is where `custom-module-templates.rst` and `custom-class-template.rst` come from.
* This causes all of the python code to be indexed and added to the [Module Index](https://google-cloud-opentelemetry--39.org.readthedocs.build/en/39/py-modindex.html) sphinx creates.
* I also added an [API Reference](https://google-cloud-opentelemetry--39.org.readthedocs. …

Docs updates with automatic API docs, pypi links, and contributing.md

---

get_mock_server.sh
opentelemetry-exporter-cloud-trace/tests/test_integration_cloud_trace_exporter.py
tox.ini

We'd like to integrate [our mock server](https://docs.google.com/document/d/1ZUwuqKIcTjrR32oxKwJw8XFNThQ8qDm_KvmTzzgiwtQ/edit#heading=h.h76dy5b7dqq2) into the Python exporter to be used for integration testing.
To setup the server, Tox will curl the binaries from [our repository](https://github.com/googleinterns/cloud-operations-api-mock). Then, the tests themselves will spin up the server, run the integration tests, and teardown the server.
Currently, the integration test just calls the mock server with the translated spans to verify that they follow the correct format and that the exporter has translated the spans properly. In the future, more tests can be added as needed

Add integration tests for trace using mock server

---

opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/__init__.py

Previously, every call to `resource.labels` would deepcopy all of the resource's labels due to the core implementation of Resources. We make this change to only deepcopy it once.

dont deepcopy resource labels multiple times

---

dev-constraints.txt

Opentelemetry python are doing a release later today. Want to bump our version in preparation and make sure all tests are passing at open-telemetry/opentelemetry-python@8bc7786b191b4f1b1f161de983db71643bf9f51e

bump ot commit to open-telemetry/opentelemetry-python@8bc7786b191b4f1b1f161de983db71643bf9f51e

---

opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-cloud-trace/tests/test_cloud_trace_exporter.py

OT attribute values support having a sequence of primitives (list of ints, tuple of floats, etc). Cloud Trace does NOT support having a list of things as an attribute value, so we would ignore these values. This PR makes it so, instead of ignoring these, we convert them to a string and send it off as usual.

add support for list attribute values

---

opentelemetry-exporter-google-cloud/setup.cfg
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/tests/test_cloud_trace_exporter.py

google-cloud-trace has updated to [version 0.24.0](https://pypi.org/project/google-cloud-trace/) and now supports passing in SpanKind information. This PR updates the cloud trace exporter to send this SpanKind info out.

Add spankind support

---

opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring_exporter_integration.py
opentelemetry-exporter-google-cloud/tests/test_integration_cloud_trace_exporter.py
test-common/MANIFEST.in
test-common/setup.cfg
test-common/setup.py
test-common/src/test_common/__init__.py
test-common/src/test_common/base_exporter_integration_test.py
tox.ini

Close #46 
Created a new package `test-common` (with `setup.py`) that is only used for an editable install in the test virtualenvs. It is not published to pypi.
The other option was to set `PYTHONPATH`, but I think this is a little clearer and also its what opentelemetry-python does.

Share common test utils

---

.circleci/config.yml
dev-constraints.txt
docs/examples/cloud_monitoring/basic_metrics.py
docs/examples/tools/cloud_resource_detector/resource_detector_metrics.py
docs/examples/tools/cloud_trace_propagator/client.py
docs/examples/tools/cloud_trace_propagator/server.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring.py
opentelemetry-exporter-google-cloud/tests/test_cloud_trace_exporter.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/cloud_trace_propagator.py
opentelemetry-tools-google-cloud/tests/test_gcp_resource_detector.py
tox.ini

Fixes #68, #70
*Depends on #72, so you will see those changes included here until it is merged and I can rebase this PR.*
OTel python 0.13b0 should be coming soon. This PR bumps the pinned version that this repo is built against to a commit from today. Most of the changes are just from renamed things from the spec. See individual points in the issue.

Breaking changes 0.13b0

---

dev-constraints.txt
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring_exporter_integration.py
opentelemetry-exporter-google-cloud/tests/test_cloud_trace_exporter.py
opentelemetry-exporter-google-cloud/tests/test_integration_cloud_trace_exporter.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/cloud_trace_propagator.py
opentelemetry-tools-google-cloud/tests/test_cloud_trace_propagator.py

Fixes #78. Main changes:
- `Span.get_context() -> Span.get_span_context()`
- `MetricRecord` now has a `Resource`, so updated the test code
- `Span` was made uninstantiable (per the spec) and instead a private `_Span` subclass is instantiable. We use this only in tests

fix breakages for opentelemetry v0.14b0

---

opentelemetry-exporter-google-cloud/setup.cfg
opentelemetry-tools-google-cloud/setup.cfg

Python 3.4 support was already dropped, but I forgot to remove it from the `setup.cfg` file.

drop python3.4 and fix spacing in setup files

---

get_mock_server.sh
opentelemetry-exporter-google-cloud/CHANGELOG.md
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring_exporter_integration.py
opentelemetry-tools-google-cloud/CHANGELOG.md
test-common/src/test_common/base_exporter_integration_test.py
tox.ini

There were some more breakages from v0.14b0 that needed fixing before release. Most of this PR is updating tests to actually catch the breakages in the future.
- Updated unit tests to use autospeccing
- Update the integration tests against GCM Mock api to catch the errors too
* turns out the cloud monitoring integration tests were passing even though they shouldn't, because we swallow exceptions when `CreateMetricDescriptor()` fails
* updated tests to fail if there is an error logged from `CreateMetricDescriptor()` failure
* updated tests/exporter to actually pass
- Updated changelogs

fixed more 0.14b0 breakages and updated tests to catch them

---

dev-constraints.txt
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring_exporter_integration.py
opentelemetry-exporter-google-cloud/tests/test_cloud_trace_exporter.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/cloud_trace_propagator.py
opentelemetry-tools-google-cloud/tests/test_cloud_trace_propagator.py

Update for breakages in opentelemetry core 0.15b0 packages. Also tested things manually with a sample app exporting to Cloud Trace and Monitoring.

upgrade packages for opentelemetry-python 0.15b0

---

docs/conf.py
docs/examples/cloud_trace_exporter/advanced_trace.py
docs/examples/cloud_trace_exporter/basic_trace.py
get_mock_server.sh
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/resource_detector.py
release.py
test-common/setup.py
test-common/src/test_common/__init__.py
test-common/src/test_common/base_exporter_integration_test.py

- Add google copyright headers to files missing it
- ~`s/Copyright\ OpenTelemetry\ Authors/Copyright 2021 Google/` – is this ok or should it be put off for later? (@punya)~

add missing copyright headers, change OpenTelemetry copyright to Google

---

.pylintrc

I could not remove "MASTER" because it is part of the pylintrc config format ([see here](https://github.com/PyCQA/pylint/blob/8649b721560ac33756792e405a6d7bbf7d331e57/pylint/constants.py#L39))
The same issue exists in OTel python https://github.com/open-telemetry/opentelemetry-python/issues/1076

remove non-inclusive language from pylintrc where possible

---

.github/header-checker-lint.yml
dev-constraints.txt
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/cloud_trace_propagator.py

- Upgrade to latest python SDK
- Add fields
- Typing improvements
Header checker is failing because the modified files are copyrighted to OpenTelemetry Authors.
#97

upgrade OTel python to 0.17b0, small fixes

---

opentelemetry-exporter-google-cloud/setup.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/google/version.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring.py
opentelemetry-tools-google-cloud/setup.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/google/version.py

header-checker-lint requires a year in its copyright regex: https://github.com/googleapis/repo-automation-bots/blob/7999fc36b64ded184fbba54dd606633b98e291f7/packages/header-checker-lint/src/header-parser.ts#L23
And the checker passes on this PR

Add year to OpenTelemetry Authors copyright header for lint checker

---

docs/examples/cloud_monitoring/basic_metrics.py
docs/examples/tools/cloud_resource_detector/resource_detector_metrics.py
docs/examples/tools/cloud_resource_detector/resource_detector_trace.py
docs/examples/tools/cloud_trace_propagator/client.py
docs/examples/tools/cloud_trace_propagator/server.py
opentelemetry-exporter-google-cloud/setup.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/google/version.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring.py
opentelemetry-exporter-google-cloud/tests/test_cloud_monitoring_exporter_integration.py
opentelemetry-exporter-google-cloud/tests/test_cloud_trace_exporter.py
opentelemetry-exporter-google-cloud/tests/test_integration_cloud_trace_exporter.py
opentelemetry-tools-google-cloud/setup.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/cloud_trace_propagator.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/google/version.py
opentelemetry-tools-google-cloud/tests/test_cloud_trace_propagator.py
opentelemetry-tools-google-cloud/tests/test_gcp_resource_detector.py

Missed some of the headers in #103 because they had "The" in front... This is hopefully the last of them, all standardized to the same format...
```sh
perl -i -p -e 's/Copyright\ .*OpenTelemetry.*$/Copyright 2021 The OpenTelemetry Authors/' `git ls-files`
```

Standardize existing "OpenTelemetry Authors" copyrights

---

docs/examples/cloud_monitoring/basic_metrics.py
docs/examples/tools/cloud_resource_detector/resource_detector_metrics.py
opentelemetry-exporter-google-cloud/README.rst

Update example codes, the "create_metric" no longer exists in the latest version.

Update example codes, the "create_metric" no longer exists.

---

.github/header-checker-lint.yml
dev-constraints.txt

The existing copyright headers have "The" which was missing e.g.:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/286db5b37eb990937ef9c16466d06e75ac03b212/opentelemetry-tools-google-cloud/src/opentelemetry/tools/cloud_trace_propagator.py#L1
Tested with [the JS regex](https://github.com/googleapis/repo-automation-bots/blob/28087753bb56a2da23f315892b425933053e1002/packages/header-checker-lint/src/header-parser.ts#L23):
```console
$ node
Welcome to Node.js v12.20.1.
Type ".help" for more information.
>
>
> const COPYRIGHT_REGEX = /\s*([*#]|\/\/) \s*Copyright (\d{4}(-\d{4})?) ([\w\s]+)\.?/;
undefined
> let line = "# Copyright 2021 The OpenTelemetry Authors";
undefined
> line.match(COPYRIGHT_REGEX)
[
'# Copyright 2021 The OpenTelemetry Authors',
'#',
'2021', …
```

add "The" to copyright check "The OpenTelemetry Authors"

---

opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/tests/test_cloud_trace_exporter.py
opentelemetry-tools-google-cloud/CHANGELOG.md

Fixes #105 
Map status correctly. [Typescript impl for reference](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/b774e94908c546d4287da65602c4ab25dfd6e025/packages/opentelemetry-cloud-trace-exporter/src/transform.ts#L80-L94).

Map span status properly to GCT

---

.circleci/config.yml
.flake8
dev-constraints.txt
docs/contributing.md
opentelemetry-exporter-google-cloud/setup.cfg
opentelemetry-tools-google-cloud/setup.cfg
tox.ini

Fixes #19 
Instead of running lint, mypy, and fix globally over the whole repo, they are now scoped per package and have distinct virtualenvs.
This is needed before splitting up all the packages because the metrics and trace exporters will depend on conflicting versions of `opentelemetry-api`. Also simplified the tox file a good amount.

run lint, mypy, fix tox jobs per package instead of in a single env

---

.circleci/config.yml
.pylintrc
dev-constraints.txt
opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-trace/CHANGELOG.md
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-tools-google-cloud/CHANGELOG.md
opentelemetry-tools-google-cloud/setup.cfg
tox.ini

drop python3.5 add python3.9

---

docs/contributing.md
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/_time.py
opentelemetry-exporter-gcp-monitoring/tests/test_cloud_monitoring.py
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_exporter.py
opentelemetry-exporter-gcp-trace/tests/test_integration_cloud_trace_exporter.py
opentelemetry-propagator-gcp/setup.cfg
opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/__init__.py
opentelemetry-propagator-gcp/tests/test_cloud_trace_propagator.py
opentelemetry-resourcedetector-gcp/setup.cfg
tox.ini

- Updated packages for 1.x OTel releases
- Trace exporter, propagator, and resource detector depend on `~=1.0`
- Metric exporter depends on `~=1.10a0` which contains metrics API/SDK now upstream
- Mostly propagator changes and renames
- Create a single dev env again in tox

Update packages to 1.x OTel releases

---

opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
opentelemetry-exporter-gcp-trace/CHANGELOG.md
opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
opentelemetry-propagator-gcp/CHANGELOG.md
opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
opentelemetry-resourcedetector-gcp/CHANGELOG.md
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py

Please review the two comments individually:
- Release 1.0.0rc0 (Part 1/2) release commit
- Release 1.0.0rc0 (Part 2/2) bump version to 1.1.0.dev0
This PR generated by `release.py` script in PR #132 with
```bash
./release.py \
--release_version 1.0.0rc0 \
--new_dev_version 1.1.0.dev0 \
--alternate_suffix 'opentelemetry-exporter-gcp-monitoring:a0' \
--alternate_suffix 'opentelemetry-resourcedetector-gcp:a0'
```
----
The packages versions released from here is
- 1.0.0rc0 (release candidate) for `opentelemetry-propagator-gcp` and `opentelemetry-exporter-gcp-trace`
- 1.0.0a0 (alpha) for `opentelemetry-resourcedetector-gcp` and `opentelemetry-exporter-gcp-monitoring`

release pr/1.0.0rc0

---

docs/releasing.md
release.py

- Remove pinning stuff, as its no longer needed
- Can now specify alternate suffixes for certain packages. This is in line with what our ops-java repo does, where metrics and resource detector are marked alpha, but otherwise the same version. See updated `releasing.md` for explanation
- Verify everything is PEP440/pypi compliant now
Release PR generated from these changes here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/135

Update releasing script to allow specifying suffixes for different packages

---

opentelemetry-propagator-gcp/CHANGELOG.md
opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/__init__.py
opentelemetry-propagator-gcp/tests/test_cloud_trace_propagator.py

This issue was found for OTel propagators https://github.com/open-telemetry/opentelemetry-python/issues/1765
Propagators should
- Use an empty context if none is passed
- Only return a new modified context if it successfully `extract()`ed.

Propagator return original context if failed to extract

---

opentelemetry-exporter-cloud-monitoring/README.rst
opentelemetry-exporter-cloud-monitoring/setup.cfg
opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
opentelemetry-exporter-cloud-monitoring/tests/__init__.py
opentelemetry-exporter-cloud-trace/README.rst
opentelemetry-exporter-cloud-trace/setup.cfg
opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-cloud-trace/src/opentelemetry/exporter/cloud_trace/version.py
opentelemetry-exporter-cloud-trace/tests/__init__.py

I created a new orphan branch with the old code (it was in opentelemetry-python upstream repo) [final-release-old-exporters-0.10b1](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/tree/final-release-old-exporters-0.10b1). This PR modifies that to warn in code and in the READMEs on pypi that this package is deprecated and what to use instead.
I also bumped the versions to `0.10b1`. I'll release these packages once more with just these modifications. You can ignore test failures, this code doesn't have any CI stuff.

add deprecation warnings for opentelemetry-exporter-cloud-monitoring and opentelemetry-exporter-cloud-trace

---

opentelemetry-exporter-google-cloud/README.rst
opentelemetry-exporter-google-cloud/setup.cfg
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/google/version.py
opentelemetry-tools-google-cloud/README.rst
opentelemetry-tools-google-cloud/setup.cfg
opentelemetry-tools-google-cloud/src/opentelemetry/tools/cloud_trace_propagator.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/google/version.py
opentelemetry-tools-google-cloud/src/opentelemetry/tools/resource_detector.py

Same changes as #142 but for opentelemetry-exporter-google-cloud and opentelemetry-tools-google-cloud with final release version 0.18b1. These packages are deprecated.

add deprecation warnings for opentelemetry-exporter-google-cloud and opentelemetry-tools-google-cloud

---

cloudbuild-e2e-gce.yaml
cloudbuild-e2e-gke.yaml
cloudbuild-e2e-local.yaml
cloudbuild.yaml
e2e-test-server/wait-for-image.sh

- Move the docker build step into its own yaml
- Make individual build triggers and yaml files for each of local, gce, gke. Each of these block on the docker build (with timeout)

Run e2e tests on gke and gce

---

dev-constraints.txt

For some reason, lint is failing in main branch even though we didn't change anything. Bumping the version solved it

bump pylint version to fix lint failures

---

e2e-test-server/constraints.txt
opentelemetry-exporter-gcp-trace/CHANGELOG.md
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_exporter.py
opentelemetry-exporter-gcp-trace/tests/test_integration_cloud_trace_exporter.py

Fixes #164 
- Updated dependency specifier to newer version
- New client library versions use proto-plus generated classes, which don't mix well with dictionaries (see https://github.com/googleapis/proto-plus-python/issues/161) so updated code to use the generated types

Upgrade google-cloud-trace dep to ~=1.1

---

dev-constraints.txt
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py

- See https://github.com/psf/black/issues/2964
- And tightened version specifier for Cloud Monitoring exporter which uses a very outdated version of opentelemetry (old metrics impl)

Fix build dependency issues

---

docs/cloud_trace/cloud_trace_propagator.rst
docs/index.rst
opentelemetry-propagator-gcp/setup.cfg
opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/__init__.py
opentelemetry-propagator-gcp/tests/test_cloud_trace_propagator_auto_instrument.py

Like #179, this makes it possible to use the trace propagator with environment variables and auto instrumentation. Updated docs can be seen at https://output.circle-artifacts.com/output/job/d6949a7c-a9af-4cea-bc6c-89aa4e22fbd6/artifacts/0/docs-html/cloud_trace/cloud_trace_propagator.html

Add entry point for x-cloud-trace-context propagator

---

opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/__init__.py
opentelemetry-resourcedetector-gcp/tests/test_gcp_resource_detector.py

- If the env `CONTAINER_NAME` is not found, it is not set, instead of silently disabling the resource detector all together.
- This makes the behavior consistent with https://github.com/GoogleCloudPlatform/opentelemetry-operations-go.

Update no container name behaviour

---

cloudbuild-e2e-gce.yaml
opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_auto_instrument.py

call to `_import_exporters()` is missing a positional arg, as reported by [this failing PR test](https://app.circleci.com/pipelines/github/GoogleCloudPlatform/opentelemetry-operations-python/731/workflows/8cc32f9e-88f5-4e1e-bc2f-66f8c52a8736/jobs/4816) also verified locally on a clean checkout.

fix auto-instrument loading tests for trace exporter.

---

opentelemetry-propagator-gcp/README.rst
opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/__init__.py

Also adds usage information to README.rst for both propagators.

Create a Readonly Propagator to match the golang "One Way" propagator.

---

.circleci/config.yml
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-propagator-gcp/setup.cfg
opentelemetry-resourcedetector-gcp/setup.cfg
tox.ini

This follows the supported versions in upstream OTel python.

Drop support for Python 3.6, add 3.10 and 3.11

---

.circleci/config.yml
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-propagator-gcp/setup.cfg
opentelemetry-resourcedetector-gcp/setup.cfg
tox.ini

Until https://github.com/googleapis/proto-plus-python/issues/326 is fixed, client libraries don't properly support 3.11

Drop python3.11 temporarily

---

dev-constraints.txt
opentelemetry-exporter-gcp-monitoring/tests/__snapshots__/test_cloud_monitoring/test_counter.json
opentelemetry-exporter-gcp-monitoring/tests/conftest.py
opentelemetry-exporter-gcp-monitoring/tests/fixtures/gcmfake.py
opentelemetry-exporter-gcp-monitoring/tests/fixtures/snapshot_gcmcalls.py
opentelemetry-exporter-gcp-monitoring/tests/test_cloud_monitoring.py
tox.ini

This is very similar to what we've done for the collector integration tests in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/main/exporter/collector/integrationtest/testdata/fixtures/metrics
Implemented one basic test with a counter. I will add more tests in the next PR

Add snapshot test setup code and basic tests

---

opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py

There's no need to stop sending MetricKind, as we actually do that in
the [collector](https://cs.github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/e955c204f4f2bfdc92ff0ad52786232b975efcc2/exporter/metric/metric.go?q=createtimeseries#L479).
I don't think it's worth keeping a todo around.

Remove todo comment that is no longer applicable

---

opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-gcp-monitoring/tests/__snapshots__/test_cloud_monitoring/test_invalid_label_keys.json
opentelemetry-exporter-gcp-monitoring/tests/test_cloud_monitoring.py
opentelemetry-exporter-gcp-monitoring/tests/test_normalize_label_key.py

Implementation copied from the Go exporter https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/e955c204f4f2bfdc92ff0ad52786232b975efcc2/exporter/metric/metric.go#L595-L604

Normalize invalid label keys

---

opentelemetry-resourcedetector-gcp/CHANGELOG.md
opentelemetry-resourcedetector-gcp/setup.cfg
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_detector.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_gce.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_metadata.py
opentelemetry-resourcedetector-gcp/tests/__snapshots__/test_detector.ambr
opentelemetry-resourcedetector-gcp/tests/test_detector.py
opentelemetry-resourcedetector-gcp/tests/test_gce.py

Mostly just copied from the JS implementation. Note Google doesn't provide a metadata library we can use here directly like we have in Go and JS.
After I have implemented GKE detection, I will replace the existing (unstable) impl with the spec compliant one and update the trace exporter and e2e tests.

Add spec compliant GCE detection

---

cloudbuild-e2e-cloud-run.yaml
cloudbuild-e2e-gce.yaml
cloudbuild-e2e-gke.yaml
cloudbuild-e2e-local.yaml
e2e-test-server/e2e_test_server/scenarios.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_metadata.py

It is successfully detecting on GKE, GCE. Will add GCR and other serverless in follow up PRs.

Implement resource detection e2e scenario

---

.github/workflows/ci.yaml
opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-trace/CHANGELOG.md
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-propagator-gcp/CHANGELOG.md
opentelemetry-propagator-gcp/setup.cfg
opentelemetry-resourcedetector-gcp/CHANGELOG.md
opentelemetry-resourcedetector-gcp/setup.cfg
tox.ini

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/206

Add support for python 3.11

---

docs/examples/cloud_monitoring/README.rst
docs/examples/cloud_resource_detector/README.rst
docs/examples/cloud_trace_exporter/README.rst
docs/examples/cloud_trace_propagator/README.rst
docs/examples/flask_e2e/README.rst
docs/examples/prometheus_exemplars/README.rst

staged at https://google-cloud-opentelemetry--247.org.readthedocs.build/en/247/
- Reword instructions for getting Application Default Credentials
- Removed instructions to enable Trace/Monitoring APIs since they are [enabled by default](https://cloud.google.com/service-usage/docs/enabled-service#default)
- Fixed list RST markup through all documents to remove ugly indentation

Update example setup instructions for getting GCP credentials

---

opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
opentelemetry-exporter-gcp-trace/CHANGELOG.md
opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
opentelemetry-propagator-gcp/CHANGELOG.md
opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
opentelemetry-resourcedetector-gcp/CHANGELOG.md
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py

- Release 1.5.0 (Part 1/2) release commit
- Release 1.5.0 (Part 2/2) bump version to 1.6.0.dev0
Created following https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/docs/releasing.md

release pr/1.5.0

---

dev-constraints.txt
opentelemetry-resourcedetector-gcp/tests/__snapshots__/test_detector.ambr

Pinning the version should prevent the user agent strings from breaking every tiem a new release is made. The pinned version should be regularly bumped (dependabot or renovate would work nice here).

Update snapshot tests and pin upstream versions

---

tox.ini

The fix in #254 didn't apply to tox environments that run `pip install .`
In #256 `test_detects_gce` was failing with opentelemetry-sdk version 1.19.0 instead of 1.18.0
Also fix `get_mock_server.sh` not being in `allowlist_externals`

Pin upstream version of opentelemetry when running tests

---

opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py
opentelemetry-exporter-gcp-trace/tests/test_cloud_trace_exporter.py
tox.ini

Similar to discussion at googleapis/python-api-core#27 I am using opentelemetry in an environment where modules are vendored without pip. So, pkg_resources can not be used to search for a module at runtime to get its version.

Don't use `pkg_resources.get_distribution(..).version`

---

.github/workflows/ci.yaml

https://github.com/rpkilby/tox-factor/issues/18
Just cleaning up – doesn't appear to break anything as-is with version 3.

Remove tox pin to version 3, as tox-factor is no longer required in 4

---

docs/contributing.md

This is no longer necessary with tox version 4, and creates a confusing error message.
https://github.com/rpkilby/tox-factor/issues/18

Remove instruction to install `tox-factor`

---

opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_constants.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_mapping.py
opentelemetry-resourcedetector-gcp/tests/__snapshots__/test_mapping.ambr
opentelemetry-resourcedetector-gcp/tests/test_mapping.py

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/272
Question: should faas.* attributes take precedence over service.* attributes if they are present?  If they do, it might break users who are currently using service.* attributes.  If we don't, the default service (unknown) will take precedence over faas.name

Map faas.* attributes to generic_task in resource mapping

---

opentelemetry-exporter-gcp-monitoring/CHANGELOG.md
opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/version.py
opentelemetry-exporter-gcp-trace/CHANGELOG.md
opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/version.py
opentelemetry-propagator-gcp/CHANGELOG.md
opentelemetry-propagator-gcp/src/opentelemetry/propagators/cloud_trace_propagator/version.py
opentelemetry-resourcedetector-gcp/CHANGELOG.md
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/version.py

- Release 1.6.0 (Part 1/2) release commit
- Release 1.6.0 (Part 2/2) bump version to 1.7.0.dev0
Created following [releasing.md](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/docs/releasing.md). Will be merged with "Rebase and Merge" to generate two commits in main

release pr/1.6.0

---

.readthedocs.yml

Seeing this in the failed builds:
> The configuration key "build.image" is deprecated. Use "build.os" instead to continue building your project. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
Updating following [this](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#use-a-requirements-file-for-python-dependencies). Build passed on ReadTheDocs: https://readthedocs.org/projects/google-cloud-opentelemetry/builds/22257801/

Fix ReadTheDocs config

---

dev-constraints.txt

Upgrade sphinx to fix docs build which was failing with
```    
docs-ci: commands[0]> make -C docs/ clean html    
make: Entering directory '/home/runner/work/opentelemetry-operations-python/opentelemetry-operations-python/docs'    
Running Sphinx v4.3.1    
Sphinx version error:    
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.    
make: *** [Makefile:20: html] Error 2    
make: Leaving directory '/home/runner/work/opentelemetry-operations-python/opentelemetry-operations-python/docs'    
docs-ci: exit 2 (0.85 seconds) /home/runner/work/opentelemetry-operations-python/opentelemetry-operations-python> make -C docs/ clean html pid=1886    
docs-ci: FAIL code 2 (16.84=setup[15.99]+cmd[0.85] seconds) …
```

Upgrade sphinx to fix docs build

---

samples/otlptrace/example.py

Following some examples from https://opentelemetry.io/docs/languages/python/instrumentation/, https://opentelemetry.io/docs/languages/python/exporters/#otlp-dependencies, https://github.com/googleapis/google-auth-library-python/blob/main/samples/cloud-client/snippets/authenticate_explicit_with_adc.py, and https://googleapis.dev/python/google-auth/latest/user-guide.html#requests to try to get a Google auth client and pass the headers in exporter requests

Add OTLP trace sample with GCP auth

---

samples/instrumentation-quickstart/Dockerfile
samples/instrumentation-quickstart/README.md
samples/instrumentation-quickstart/app.py
samples/instrumentation-quickstart/docker-compose.creds.yaml
samples/instrumentation-quickstart/docker-compose.yaml
samples/instrumentation-quickstart/otel-collector-config.yaml
samples/instrumentation-quickstart/requirements.txt

This is mostly boilerplate to make future PRs smaller.
The following are taken from https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/309:
* `samples/instrumentation-quickstart/Dockerfile`
* `samples/instrumentation-quickstart/app.py`
The following are minimally adapted from the java quickstart:
* samples/instrumentation-quickstart/README.md
* samples/instrumentation-quickstart/docker-compose.creds.yaml
* samples/instrumentation-quickstart/docker-compose.yaml
The quickstart runs and serves requests, but does not currently include any instrumentation.  The logs are also not in the correct format.
~~I noticed we have some examples in docs/examples, and another example in /samples.  Should we consolidate?~~

Add WIP instrumentation quickstart sample

---

samples/instrumentation-quickstart/app.py
samples/instrumentation-quickstart/requirements.txt

Adds flask and requests instrumentation, and configures the OpenTelemetry trace and metrics SDK

Add metrics and traces to the OTel quickstart using flask instrumentation

---

samples/instrumentation-quickstart/app.py
samples/instrumentation-quickstart/requirements.txt

This uses `python-json-logger` to do the json formatting, and changes the keys used to match what GCP expects.  All loglevels seem to work properly.  I did not investigate other logging libraries, since the existing GCP docs already recommend using `logging`.
The second commit adds the trace context keys.  I used `opentelemetry-instrumentation-logging` to make the keys available to the logger, and used `rename_fields` to set the proper GCP keys for the trace context.

Add json logging to the sample application

---

dev-constraints.txt
tox.ini

This makes testing a bit faster and allows pip to fully consider all dependencies at once. It also makes tox.ini compatible with [tox-uv](https://github.com/tox-dev/tox-uv) which is handy for speeding up local runs.

Update tox.ini to not use separate pip steps

---

samples/instrumentation-quickstart/Dockerfile
samples/instrumentation-quickstart/app.py
samples/instrumentation-quickstart/docker-compose.yaml
samples/instrumentation-quickstart/otel-collector-config.yaml
samples/instrumentation-quickstart/requirements.txt

Changes:
* Use gunicorn
* Manually configure the resource in the app instead of using the OTEL_SERVICE_NAME env var.
* Use the PID as the service.instance.id to avoid duplicate timeseries errors.
* Change the `resource` processor in the collector to provide defaults, and not to override the resource from the application

Change the sample to use gunicorn

---

samples/instrumentation-quickstart/app.py
samples/instrumentation-quickstart/gcp_logging.py
samples/instrumentation-quickstart/setup_opentelemetry.py

Changes:
* Split logging and OTel setup into their own files
* remove unneeded `logging.getLogger('werkzeug').setLevel(logging.ERROR)` line.
* Use `logging.basicConfig(` to configure the handler globally, instead of only configuring the handler in the app file.
* Add tags so this can be used in GCP documentation

Clean up sample, and add tags

---

.dockerignore
cloudbuild-e2e-cloud-functions-gen2.yaml
e2e-test-server/Dockerfile
e2e-test-server/constraints.txt
e2e-test-server/e2e_test_server/constants.py
e2e-test-server/e2e_test_server/server.py
e2e-test-server/main.py
e2e-test-server/requirements-dockerfile.txt
e2e-test-server/requirements-shared.txt
e2e-test-server/requirements.txt

Adds cloud build yaml for cloud functions which builds wheels of the dependent monorepo dependencies for testing. Implemented a Cloud Functions handler for testing.
Manually verified the e2e test generated span:

Run e2e tests on Cloud Functions

---

opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_constants.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_detector.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_gae.py
opentelemetry-resourcedetector-gcp/tests/__snapshots__/test_detector.ambr
opentelemetry-resourcedetector-gcp/tests/test_detector.py
opentelemetry-resourcedetector-gcp/tests/test_gae.py

More or less copied from the Go/JS implementations.
Please ignore the **ops-python-e2e-gae (opentelemetry-ops-e2e)** failure. E2e tests are added in the next PR https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/350

Implement GAE resource detection

---

cloudbuild-e2e-gae-standard.yaml

The build script is copied from Cloud Functions yaml which also builds a source zip with monorepo dependencies packaged in

Run e2e tests on GAE standard

---

cloudbuild-e2e-cloud-functions-gen2.yaml
cloudbuild-e2e-cloud-run.yaml
cloudbuild-e2e-gae.yaml
cloudbuild-e2e-gce.yaml
cloudbuild-e2e-gke.yaml
cloudbuild-e2e-image.yaml
cloudbuild-e2e-local.yaml
e2e-test-server/wait-for-image.sh

- Push images to GAR
- Upgrading to latest test runner docker image which lives in GAR
- Update `wait-for-image.sh` and build scripts that were coupled to gcr.

Migrate from gcr.io to Artifact Registry

---

docs/index.rst
opentelemetry-exporter-gcp-monitoring/README.rst
opentelemetry-exporter-gcp-trace/README.rst
opentelemetry-propagator-gcp/README.rst
opentelemetry-resourcedetector-gcp/README.rst

Forgot these in #358. The README.rst files are what appears on PyPI, and the index.rst is for https://google-cloud-opentelemetry.readthedocs.io/

Add links to quickstart and observability overview PyPI README.rst and sphinx docs

---

opentelemetry-resourcedetector-gcp/CHANGELOG.md
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_metadata.py

Use a shorter timeout of 2 seconds for the connection before the 5 seconds read one to avoid blocking too much if the metadata server is not available.
This makes the code behave more similar to the go one: https://github.com/googleapis/google-cloud-go/blob/main/compute/metadata/metadata.go#L65

Use a shorter timeout for the metadata endpoint

---

samples/instrumentation-quickstart/docker-compose.yaml
samples/instrumentation-quickstart/otel-collector-config.yaml
samples/instrumentation-quickstart/requirements.txt

I'm trying to debug a customer issue with the python SDK + GMP exporter with exponential histograms, so i'm updating the sample to use exponential histograms.
I verified that exponential histogram  can be queried using both MQL and promql (using histogram_quantile).

Update instrumentation sample to use exponential histograms

---

.github/workflows/ci.yaml
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-propagator-gcp/setup.cfg
opentelemetry-resourcedetector-gcp/setup.cfg
tox.ini

This fixes failing CI checks.
- Pinning ubuntu to 22.04 so that python 3.7 is still available (https://github.com/actions/setup-python/issues/962). We should eventually drop 3.7 (https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/367), which is EOL.
- Start testing python 3.13 while we're at it

Fix CI and test with python 3.13

---

e2e-test-server/e2e_test_server/scenarios.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_detector.py
opentelemetry-resourcedetector-gcp/tests/__snapshots__/test_detector.ambr

We should create a Resource instance and not use Resource.create because if we set OTEL_EXPERIMENTAL_RESOURCE_DETECTORS we will go into an infinite loop trying to load and instantiate all the resources detectors.
See [Resource.create implementation](https://github.com/open-telemetry/opentelemetry-python/blob/b48223561acfdffd1411ed7d015ddabe6f6eb801/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L172)
Fix #363

Fix creation of resources in _detector

---

samples/otlpmetric/README.md
samples/otlpmetric/example.py
samples/otlpmetric/requirements.txt

TESTED=manually tested against staging

feat: add otlp metric sample with gcp auth

---

samples/instrumentation-quickstart/setup_opentelemetry.py

This is not used in the quickstart code itself, but GenAI instrumentations do use it. We want users to use this proper setup code.

Setup OTel logs and events in quickstart

---

samples/instrumentation-quickstart/app.py
samples/instrumentation-quickstart/gcp_logging.py
samples/instrumentation-quickstart/setup_opentelemetry.py

No functional changes here, I just moved the initialization code into functions to be called (instead of import side effects) and auto-formatted the code.

Fix lint and style issues and quickstart with ruff

---

.github/workflows/ci.yaml
opentelemetry-exporter-gcp-logging/setup.cfg
opentelemetry-exporter-gcp-monitoring/setup.cfg
opentelemetry-exporter-gcp-trace/setup.cfg
opentelemetry-propagator-gcp/setup.cfg
opentelemetry-resourcedetector-gcp/setup.cfg
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_gke.py
opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_metadata.py
tox.ini

This follows upstream otel python dropping support for it.

Drop support for python3.7

---

opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py
opentelemetry-exporter-gcp-monitoring/tests/__snapshots__/test_cloud_monitoring/test_exponential_histogram.json
opentelemetry-exporter-gcp-monitoring/tests/test_cloud_monitoring.py

Fix for https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/357. Based on the Go / TS implementations, https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/d6795b491c748855e4a4d6eec07ae2cb44a78da1/exporter/metric/metric.go#L723.
I've tested this on a small app, and it seems to work fine.

Add support for exponential histograms
